/**
 * hoolix completion <shell>
 *
 * Generate shell completion scripts that provide:
 *   - Command / subcommand completion
 *   - Dynamic server slug completion (via `hoolix list --json`)
 *   - Dynamic template ID completion (via `hoolix templates list --json`)
 *   - Client ID completion
 *   - Flag completion per-command
 *
 * Setup:
 *   bash:         eval "$(hoolix completion bash)"    # add to ~/.bashrc
 *   zsh:          eval "$(hoolix completion zsh)"     # add to ~/.zshrc
 *   fish:         hoolix completion fish | source
 *   powershell:   hoolix completion powershell | Invoke-Expression  # add to $PROFILE
 */

import { logger } from '../core/logger.js';
import { printTitle, printCommand, printDetails, ui } from '../ui/format.js';

const SUPPORTED_SHELLS = ['bash', 'zsh', 'fish', 'powershell'] as const;
type Shell = (typeof SUPPORTED_SHELLS)[number];

const COMMANDS = [
  'create', 'install', 'list', 'info', 'delete',
  'start', 'stop', 'reindex', 'verify', 'rotate',
  'connect', 'clients', 'client', 'secrets', 'trial',
  'stats', 'audit', 'export', 'import', 'bundle',
  'doctor', 'update', 'uninstall', 'gui',
  'templates', 'completion', 'version', 'help',
];

const CLIENTS = [
  'claude', 'claude-code', 'cursor', 'vscode', 'windsurf',
  'continue', 'cline', 'codex', 'grokbuild', 'generic',
];

const SLUG_COMMANDS = [
  'info', 'delete', 'start', 'stop', 'reindex',
  'verify', 'rotate', 'connect', 'export', 'audit', 'stats',
];

// ── Script generators ─────────────────────────────────────────────────────────
// NOTE: Shell `${var}` references MUST be written as `\${var}` inside TypeScript
// template literals to prevent TypeScript from treating them as interpolations.
// Plain `$var` (no braces) is fine as-is.

function bashCompletion(): string {
  const cmds    = COMMANDS.join(' ');
  const clients = CLIENTS.join(' ');
  const slugCmdCase = SLUG_COMMANDS.join('|');

  // shellcheck: ignore SC2207 — intentional word-splitting for completion
  return `# hoolix bash completion — generated by \`hoolix completion bash\`
# Add to ~/.bashrc or ~/.bash_profile:
#   eval "$(hoolix completion bash)"

_hoolix_get_slugs() {
  hoolix list --json 2>/dev/null | grep '"slug"' | sed 's/.*"slug": *"\\([^"]*\\)".*/\\1/'
}

_hoolix_get_templates() {
  hoolix templates list --json 2>/dev/null | grep '"id"' | sed 's/.*"id": *"\\([^"]*\\)".*/\\1/'
}

_hoolix_completions() {
  local cur prev first
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  first="\${COMP_WORDS[1]}"

  # First argument: top-level commands
  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=($(compgen -W "${cmds}" -- "$cur"))
    return 0
  fi

  # --client flag value
  if [[ "$prev" == "--client" ]]; then
    COMPREPLY=($(compgen -W "${clients}" -- "$cur"))
    return 0
  fi

  # Shell names after \`completion\`
  if [[ "$first" == "completion" && $COMP_CWORD -eq 2 ]]; then
    COMPREPLY=($(compgen -W "bash zsh fish powershell" -- "$cur"))
    return 0
  fi

  # Subcommands
  case "$first" in
    secrets)
      if [[ $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=($(compgen -W "list set remove" -- "$cur"))
        return 0
      elif [[ $COMP_CWORD -eq 3 ]]; then
        COMPREPLY=($(compgen -W "$(_hoolix_get_slugs)" -- "$cur"))
        return 0
      fi
      ;;
    bundle)
      if [[ $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=($(compgen -W "export import" -- "$cur"))
        return 0
      fi
      ;;
    clients)
      if [[ $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=($(compgen -W "list" -- "$cur"))
        return 0
      fi
      ;;
    client)
      if [[ $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=($(compgen -W "status" -- "$cur"))
        return 0
      fi
      ;;
    templates)
      if [[ $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=($(compgen -W "list info" -- "$cur"))
        return 0
      elif [[ $COMP_CWORD -eq 3 && "\${COMP_WORDS[2]}" == "info" ]]; then
        COMPREPLY=($(compgen -W "$(_hoolix_get_templates)" -- "$cur"))
        return 0
      fi
      ;;
    install)
      if [[ $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=($(compgen -W "$(_hoolix_get_templates)" -- "$cur"))
        return 0
      fi
      ;;
  esac

  # Slug-requiring commands: complete server slugs at position 2
  case "$first" in
    ${slugCmdCase})
      if [[ $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=($(compgen -W "$(_hoolix_get_slugs)" -- "$cur"))
        return 0
      fi
      ;;
  esac

  # Per-command flag completion
  case "$first" in
    start)    COMPREPLY=($(compgen -W "--port --transport --proxy --json" -- "$cur")) ;;
    connect)  COMPREPLY=($(compgen -W "--client --dry-run --yes --json" -- "$cur")) ;;
    create)   COMPREPLY=($(compgen -W "--url --template --source --input --credential --name --yes --json" -- "$cur")) ;;
    install)  COMPREPLY=($(compgen -W "--name --input --credential --yes" -- "$cur")) ;;
    export)   COMPREPLY=($(compgen -W "--file --team --strip-key --json" -- "$cur")) ;;
    import)   COMPREPLY=($(compgen -W "--file --slug --yes --json" -- "$cur")) ;;
    bundle)   COMPREPLY=($(compgen -W "--output --all --yes --json" -- "$cur")) ;;
    reindex)  COMPREPLY=($(compgen -W "--force --schedule --due --json" -- "$cur")) ;;
    stats)    COMPREPLY=($(compgen -W "--days --json" -- "$cur")) ;;
    audit)    COMPREPLY=($(compgen -W "--limit --tool --since --json" -- "$cur")) ;;
    delete)   COMPREPLY=($(compgen -W "--yes --json" -- "$cur")) ;;
    *)        COMPREPLY=($(compgen -W "--json --yes --help" -- "$cur")) ;;
  esac
  return 0
}

complete -F _hoolix_completions hoolix
`;
}

function zshCompletion(): string {
  const clients = CLIENTS.join(' ');
  // In zsh, we use $(hoolix ...) subshell + word splitting (IDs/slugs have no spaces)
  return `#compdef hoolix
# hoolix zsh completion — generated by \`hoolix completion zsh\`
# Add to ~/.zshrc:
#   eval "$(hoolix completion zsh)"

_hoolix_slugs() {
  hoolix list --json 2>/dev/null | grep '"slug"' | sed 's/.*"slug": *"\\([^"]*\\)".*/\\1/'
}

_hoolix_templates() {
  hoolix templates list --json 2>/dev/null | grep '"id"' | sed 's/.*"id": *"\\([^"]*\\)".*/\\1/'
}

_hoolix() {
  local state
  local -a commands

  commands=(
    'create:Create from URL, source, or template'
    'install:Install from a template (positional syntax)'
    'list:List registered MCP servers'
    'info:Show server details and status'
    'delete:Delete a server and its data'
    'start:Start MCP hosting (--proxy for mcp-server)'
    'stop:Stop a running server'
    'reindex:Refresh sources and rebuild RAG index'
    'verify:Check health and retrieval quality'
    'rotate:Rotate the Bearer auth key'
    'connect:Wire into an AI client'
    'clients:Client management (list)'
    'client:Client management (status)'
    'secrets:Credential management (list|set|remove)'
    'bundle:Multi-server bundle export/import'
    'trial:One-click demo server'
    'stats:Analytics dashboard'
    'audit:Query raw audit log'
    'export:Export a .hoolix.json bundle'
    'import:Import a .hoolix.json bundle'
    'doctor:Diagnose installation and runtime'
    'update:Check for and install updates'
    'uninstall:Remove hoolix and all data'
    'gui:Launch the local web dashboard'
    'templates:Browse templates (list|info)'
    'completion:Generate shell completion script'
    'version:Print the current version'
    'help:Show help'
  )

  _arguments -C \\
    '(-h --help)'{-h,--help}'[Show help]' \\
    '(-v --version)'{-v,--version}'[Show version]' \\
    '--json[Output JSON]' \\
    '1: :->command' \\
    '*:: :->args'

  case $state in
    command)
      _describe 'command' commands
      ;;
    args)
      local -a slugs templates subcmds
      case $words[1] in
        install)
          if [[ $CURRENT -eq 2 ]]; then
            templates=($(hoolix templates list --json 2>/dev/null | grep '"id"' | sed 's/.*"id": *"\\([^"]*\\)".*/\\1/'))
            _describe 'template ID' templates
          fi
          ;;
        info|delete|start|stop|reindex|verify|rotate|connect|export|audit|stats)
          if [[ $CURRENT -eq 2 ]]; then
            slugs=($(hoolix list --json 2>/dev/null | grep '"slug"' | sed 's/.*"slug": *"\\([^"]*\\)".*/\\1/'))
            _describe 'server slug' slugs
          fi
          if [[ $words[1] == connect ]]; then
            _arguments \\
              '--client=[Client to configure]:client:(${clients})' \\
              '--dry-run[Preview without writing]' \\
              '--yes[Skip confirmation]' \\
              '--json[JSON output]'
          fi
          if [[ $words[1] == start ]]; then
            _arguments \\
              '--port=[Port number]:port' \\
              '--transport=[Transport]:transport:(http stdio)' \\
              '--proxy[Wrap behind HTTP (mcp-server kind)]' \\
              '--json[JSON output]'
          fi
          ;;
        templates)
          if [[ $CURRENT -eq 2 ]]; then
            subcmds=('list:List all templates' 'info:Show template details')
            _describe 'subcommand' subcmds
          elif [[ $CURRENT -eq 3 && $words[2] == info ]]; then
            templates=($(hoolix templates list --json 2>/dev/null | grep '"id"' | sed 's/.*"id": *"\\([^"]*\\)".*/\\1/'))
            _describe 'template ID' templates
          fi
          ;;
        secrets)
          if [[ $CURRENT -eq 2 ]]; then
            subcmds=('list:Show credential keys' 'set:Add or rotate a credential' 'remove:Delete a credential')
            _describe 'subcommand' subcmds
          elif [[ $CURRENT -eq 3 ]]; then
            slugs=($(hoolix list --json 2>/dev/null | grep '"slug"' | sed 's/.*"slug": *"\\([^"]*\\)".*/\\1/'))
            _describe 'server slug' slugs
          fi
          ;;
        bundle)
          if [[ $CURRENT -eq 2 ]]; then
            subcmds=('export:Export multiple servers' 'import:Import a bundle file')
            _describe 'subcommand' subcmds
          fi
          ;;
        clients)
          if [[ $CURRENT -eq 2 ]]; then
            _describe 'subcommand' '(list:List supported clients)'
          fi
          ;;
        client)
          if [[ $CURRENT -eq 2 ]]; then
            _describe 'subcommand' '(status:Show wired servers)'
          fi
          ;;
        completion)
          if [[ $CURRENT -eq 2 ]]; then
            _describe 'shell' '(bash:Bash zsh:Zsh fish:Fish powershell:PowerShell)'
          fi
          ;;
      esac
      ;;
  esac
}

_hoolix "$@"
`;
}

function fishCompletion(): string {
  const cmdList = COMMANDS.map((c) => `complete -c hoolix -n __hoolix_no_subcommand -a ${c}`).join('\n');
  return `# hoolix fish completion — generated by \`hoolix completion fish\`
# Source with:
#   hoolix completion fish | source
# Or to persist across sessions:
#   hoolix completion fish > ~/.config/fish/completions/hoolix.fish

function __hoolix_slugs
  hoolix list --json 2>/dev/null | string match -r '"slug":\\s*"([^"]+)"' | string replace -r '.*"slug":\\s*"([^"]+)".*' '$1'
end

function __hoolix_templates
  hoolix templates list --json 2>/dev/null | string match -r '"id":\\s*"([^"]+)"' | string replace -r '.*"id":\\s*"([^"]+)".*' '$1'
end

function __hoolix_no_subcommand
  not __fish_seen_subcommand_from ${COMMANDS.join(' ')}
end

# Disable file completion (hoolix does not complete file paths by default)
complete -c hoolix -f

# Top-level commands
${cmdList}

# Slug-requiring commands
for cmd in ${SLUG_COMMANDS.join(' ')}
  complete -c hoolix -n "__fish_seen_subcommand_from $cmd; and test (count (commandline -opc)) -eq 2" -a "(__hoolix_slugs)"
end

# install: template IDs at position 2
complete -c hoolix -n "__fish_seen_subcommand_from install; and test (count (commandline -opc)) -eq 2" -a "(__hoolix_templates)"

# templates subcommands + info template arg
complete -c hoolix -n "__fish_seen_subcommand_from templates; and not __fish_seen_subcommand_from list info" -a "list info"
complete -c hoolix -n "__fish_seen_subcommand_from templates; and __fish_seen_subcommand_from info; and test (count (commandline -opc)) -eq 3" -a "(__hoolix_templates)"

# secrets subcommands + slug arg
complete -c hoolix -n "__fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from list set remove" -a "list set remove"
complete -c hoolix -n "__fish_seen_subcommand_from secrets; and __fish_seen_subcommand_from list set remove; and test (count (commandline -opc)) -eq 3" -a "(__hoolix_slugs)"

# bundle subcommands
complete -c hoolix -n "__fish_seen_subcommand_from bundle; and not __fish_seen_subcommand_from export import" -a "export import"

# clients / client subcommands
complete -c hoolix -n "__fish_seen_subcommand_from clients; and not __fish_seen_subcommand_from list" -a list
complete -c hoolix -n "__fish_seen_subcommand_from client; and not __fish_seen_subcommand_from status" -a status

# completion shells
complete -c hoolix -n "__fish_seen_subcommand_from completion; and test (count (commandline -opc)) -eq 2" -a "bash zsh fish powershell"

# Flags per command
complete -c hoolix -n "__fish_seen_subcommand_from connect" -l client -a "${CLIENTS.join(' ')}" -d "AI client"
complete -c hoolix -n "__fish_seen_subcommand_from start" -l port -d "Port number"
complete -c hoolix -n "__fish_seen_subcommand_from start" -l transport -a "http stdio" -d "Transport type"
complete -c hoolix -n "__fish_seen_subcommand_from start" -l proxy -d "Wrap behind HTTP (mcp-server kind)"
complete -c hoolix -n "__fish_seen_subcommand_from start" -l json -d "JSON output"
complete -c hoolix -n "__fish_seen_subcommand_from connect" -l dry-run -d "Preview without writing"
complete -c hoolix -n "__fish_seen_subcommand_from connect start delete import export bundle" -l yes -d "Skip confirmation"
complete -c hoolix -n "__fish_seen_subcommand_from create install" -l name -d "Server name"
complete -c hoolix -n "__fish_seen_subcommand_from create install" -l yes -d "Skip confirmation"
complete -c hoolix -n "__fish_seen_subcommand_from create" -l url -d "Documentation URL"
complete -c hoolix -n "__fish_seen_subcommand_from create" -l template -d "Template ID"
complete -c hoolix -n "__fish_seen_subcommand_from create install" -l input -d "Template input key=value"
complete -c hoolix -n "__fish_seen_subcommand_from create install" -l credential -d "Credential key=value"
complete -c hoolix -n "__fish_seen_subcommand_from export" -l file -d "Output file path"
complete -c hoolix -n "__fish_seen_subcommand_from export" -l team -d "Team bundle (strip embeddings)"
complete -c hoolix -n "__fish_seen_subcommand_from export" -l strip-key -d "Strip auth key from bundle"
complete -c hoolix -n "__fish_seen_subcommand_from import" -l file -d "Bundle file path"
complete -c hoolix -n "__fish_seen_subcommand_from import" -l slug -d "Override slug on import"
complete -c hoolix -n "__fish_seen_subcommand_from bundle" -l output -d "Output file path"
complete -c hoolix -n "__fish_seen_subcommand_from bundle" -l all -d "Export all servers"
complete -c hoolix -n "__fish_seen_subcommand_from reindex" -l force -d "Force full reindex"
complete -c hoolix -n "__fish_seen_subcommand_from stats" -l days -d "Number of days (default 7)"
complete -c hoolix -n "__fish_seen_subcommand_from audit" -l limit -d "Max results"
complete -c hoolix -n "__fish_seen_subcommand_from audit" -l tool -d "Filter by tool name"
complete -c hoolix -n "__fish_seen_subcommand_from audit" -l since -d "ISO date filter"
`;
}

function powershellCompletion(): string {
  // Note: PowerShell uses $var and ${var} syntax. In this TypeScript template literal,
  // we only need to escape ${var} forms (with braces) that TypeScript would misparse.
  // PowerShell's $elements, $command, $argCount etc. (no braces) are fine as-is.
  const clients = CLIENTS.map((c) => `'${c}'`).join(',');
  const slugCmds = SLUG_COMMANDS.map((c) => `'${c}'`).join(',');
  return `# hoolix PowerShell completion — generated by \`hoolix completion powershell\`
# Add to your PowerShell profile (echo $PROFILE to find the path):
#   hoolix completion powershell | Invoke-Expression

Register-ArgumentCompleter -Native -CommandName hoolix -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)

  $elements  = $commandAst.CommandElements
  $command   = if ($elements.Count -ge 2) { $elements[1].ToString() } else { '' }
  $argCount  = $elements.Count
  $prevArg   = if ($argCount -ge 2) { $elements[$argCount - 2].ToString() } else { '' }

  $allCommands = @(${COMMANDS.map((c) => `'${c}'`).join(',')})
  $slugCmds    = @(${slugCmds})
  $clients     = @(${clients})

  function Complete-Words([string[]]$words) {
    $words | Where-Object { $_ -like "$wordToComplete*" } |
      ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
  }

  function Get-HoolixSlugs {
    try {
      $json = (hoolix list --json 2>$null) -join ''
      [regex]::Matches($json, '"slug"\\s*:\\s*"([^"]+)"') | ForEach-Object { $_.Groups[1].Value }
    } catch {}
  }

  function Get-HoolixTemplates {
    try {
      $json = (hoolix templates list --json 2>$null) -join ''
      [regex]::Matches($json, '"id"\\s*:\\s*"([^"]+)"') | ForEach-Object { $_.Groups[1].Value }
    } catch {}
  }

  # First argument: top-level commands
  if ($argCount -le 2) { return Complete-Words $allCommands }

  # --client flag value
  if ($prevArg -eq '--client') { return Complete-Words $clients }

  switch ($command) {
    'install' {
      if ($argCount -eq 3) { return Complete-Words (Get-HoolixTemplates) }
    }
    { $slugCmds -contains $_ } {
      if ($argCount -eq 3) { return Complete-Words (Get-HoolixSlugs) }
      if ($_ -eq 'connect' -and $prevArg -eq '--client') { return Complete-Words $clients }
    }
    'templates' {
      if ($argCount -eq 3) { return Complete-Words @('list','info') }
      if ($argCount -eq 4 -and $elements[2].ToString() -eq 'info') { return Complete-Words (Get-HoolixTemplates) }
    }
    'secrets' {
      if ($argCount -eq 3) { return Complete-Words @('list','set','remove') }
      if ($argCount -eq 4) { return Complete-Words (Get-HoolixSlugs) }
    }
    'bundle' {
      if ($argCount -eq 3) { return Complete-Words @('export','import') }
    }
    'clients'    { if ($argCount -eq 3) { return Complete-Words @('list') } }
    'client'     { if ($argCount -eq 3) { return Complete-Words @('status') } }
    'completion' { if ($argCount -eq 3) { return Complete-Words @('bash','zsh','fish','powershell') } }
    'start'    { return Complete-Words @('--port','--transport','--proxy','--json') }
    'connect'  { return Complete-Words @('--client','--dry-run','--yes','--json') }
    'create'   { return Complete-Words @('--url','--template','--source','--input','--credential','--name','--yes','--json') }
    'export'   { return Complete-Words @('--file','--team','--strip-key','--json') }
    'import'   { return Complete-Words @('--file','--slug','--yes','--json') }
    'bundle'   { return Complete-Words @('--output','--all','--yes','--json') }
    default    { return Complete-Words @('--json','--yes','--help') }
  }
}
`;
}

// ── Command ───────────────────────────────────────────────────────────────────

export async function cmdCompletion(args: string[]): Promise<void> {
  const shell = args[1]?.toLowerCase() as Shell | undefined;

  if (!shell || !(SUPPORTED_SHELLS as readonly string[]).includes(shell)) {
    printTitle('Shell completions', 'Generate a tab-completion script for your shell.');
    printDetails([
      ['Supported', SUPPORTED_SHELLS.join(', ')],
    ]);
    console.log('');
    console.log(`  ${ui.muted('Setup (add to your shell rc file):')}`);
    console.log(`  ${ui.muted('bash:')}         eval "$(hoolix completion bash)"`);
    console.log(`  ${ui.muted('zsh:')}          eval "$(hoolix completion zsh)"`);
    console.log(`  ${ui.muted('fish:')}         hoolix completion fish | source`);
    console.log(`  ${ui.muted('powershell:')}   hoolix completion powershell | Invoke-Expression`);
    console.log('');
    console.log(`  ${ui.muted('To persist fish completions:')}`);
    printCommand('hoolix completion fish > ~/.config/fish/completions/hoolix.fish');
    console.log('');
    if (shell) {
      logger.error(`Unsupported shell: "${shell}". Choose one of: ${SUPPORTED_SHELLS.join(', ')}`);
      process.exit(1);
    }
    return;
  }

  switch (shell) {
    case 'bash':       process.stdout.write(bashCompletion()); break;
    case 'zsh':        process.stdout.write(zshCompletion());  break;
    case 'fish':       process.stdout.write(fishCompletion()); break;
    case 'powershell': process.stdout.write(powershellCompletion()); break;
  }
}
